[2025-06-29 12:45:07,575] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-06-29 12:50:55,101] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-06-29 18:54:27,559] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-06-29 19:40:42,174] [INFO] [django.utils.autoreload] /home/meeh/Desktop/venti2.0/backend/users/models.py changed, reloading.
[2025-06-29 19:40:47,938] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-06-29 19:41:16,683] [INFO] [django.utils.autoreload] /home/meeh/Desktop/venti2.0/backend/users/serializers.py changed, reloading.
[2025-06-29 19:41:20,828] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-06-29 20:01:21,527] [INFO] [django.utils.autoreload] /home/meeh/Desktop/venti2.0/backend/users/models.py changed, reloading.
[2025-06-29 20:01:29,456] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-06-29 20:04:43,808] [INFO] [django.utils.autoreload] /home/meeh/Desktop/venti2.0/backend/users/serializers.py changed, reloading.
[2025-06-29 20:04:49,446] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-06-29 20:06:43,302] [ERROR] [django.request] Internal Server Error: /api/users/users/me/
Traceback (most recent call last):
  File "/home/meeh/.local/lib/python3.12/site-packages/rest_framework/fields.py", line 437, in get_attribute
    return get_attribute(instance, self.source_attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/meeh/.local/lib/python3.12/site-packages/rest_framework/fields.py", line 104, in get_attribute
    instance = getattr(instance, attr)
               ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'AnonymousUser' object has no attribute 'email'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/meeh/.local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/meeh/.local/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/meeh/.local/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/meeh/.local/lib/python3.12/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/meeh/.local/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/meeh/.local/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/meeh/.local/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/meeh/.local/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/users/views.py", line 26, in me
    return Response(serializer.data)
                   ^^^^^^^^^^^^^^^
  File "/home/meeh/.local/lib/python3.12/site-packages/rest_framework/serializers.py", line 571, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/home/meeh/.local/lib/python3.12/site-packages/rest_framework/serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/meeh/.local/lib/python3.12/site-packages/rest_framework/serializers.py", line 525, in to_representation
    attribute = field.get_attribute(instance)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/meeh/.local/lib/python3.12/site-packages/rest_framework/fields.py", line 470, in get_attribute
    raise type(exc)(msg)
AttributeError: Got AttributeError when attempting to get a value for field `email` on serializer `UserSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `AnonymousUser` instance.
Original exception text was: 'AnonymousUser' object has no attribute 'email'.
[2025-06-29 20:07:35,393] [INFO] [django.utils.autoreload] /home/meeh/Desktop/venti2.0/backend/users/views.py changed, reloading.
[2025-06-29 20:07:40,467] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-06-29 20:11:25,128] [INFO] [django.utils.autoreload] /home/meeh/Desktop/venti2.0/backend/users/authentication.py changed, reloading.
[2025-06-29 20:11:30,666] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-06-29 20:30:39,175] [INFO] [django.utils.autoreload] /home/meeh/Desktop/venti2.0/backend/users/serializers.py changed, reloading.
[2025-06-29 20:30:45,123] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-06-29 20:40:29,892] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-06-29 20:56:07,592] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-06-29 21:05:36,913] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-06-29 21:32:40,706] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-06-29 21:40:37,252] [INFO] [django.utils.autoreload] /home/meeh/Desktop/venti2.0/backend/users/models.py changed, reloading.
[2025-06-29 21:40:45,065] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-06-29 21:44:56,058] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-06-29 21:48:05,288] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-06-29 21:53:07,074] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-06-29 21:55:27,683] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-06-29 21:56:21,489] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-06-29 22:16:36,255] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-06-29 22:22:23,567] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-06-29 22:50:07,011] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-06-29 23:32:09,947] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-06-30 10:50:13,383] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-06-30 11:07:12,695] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-06-30 12:35:39,596] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-06-30 13:51:41,473] [INFO] [django.utils.autoreload] /home/meeh/Desktop/venti2.0/backend/users/models.py changed, reloading.
[2025-06-30 13:51:46,124] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-06-30 14:07:29,683] [INFO] [django.utils.autoreload] /home/meeh/Desktop/venti2.0/backend/users/models.py changed, reloading.
[2025-06-30 14:07:38,522] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-06-30 14:51:23,602] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-06-30 14:55:51,108] [INFO] [django.utils.autoreload] /home/meeh/Desktop/venti2.0/backend/users/authentication.py changed, reloading.
[2025-06-30 14:56:02,958] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-06-30 21:39:56,929] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-06-30 21:40:53,619] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-06-30 21:54:10,421] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-07-01 14:24:30,963] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-07-03 19:34:31,531] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-07-03 21:20:12,505] [INFO] [django.utils.autoreload] /home/meeh/Desktop/venti2.0/backend/users/signals.py changed, reloading.
[2025-07-03 21:20:23,287] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-07-03 21:21:10,677] [INFO] [django.utils.autoreload] /home/meeh/Desktop/venti2.0/backend/users/models.py changed, reloading.
[2025-07-03 21:21:20,187] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-07-03 21:22:10,531] [INFO] [django.utils.autoreload] /home/meeh/Desktop/venti2.0/backend/users/views.py changed, reloading.
[2025-07-03 21:22:16,580] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-07-03 21:22:49,935] [INFO] [django.utils.autoreload] /home/meeh/Desktop/venti2.0/backend/users/admin.py changed, reloading.
[2025-07-03 21:22:55,142] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-07-03 21:24:42,554] [INFO] [django.utils.autoreload] /home/meeh/Desktop/venti2.0/backend/users/admin.py changed, reloading.
[2025-07-03 21:24:45,955] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-07-03 21:24:58,819] [INFO] [django.utils.autoreload] /home/meeh/Desktop/venti2.0/backend/users/models.py changed, reloading.
[2025-07-03 21:25:03,664] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-07-03 22:27:06,322] [INFO] [django.utils.autoreload] /home/meeh/Desktop/venti2.0/backend/users/models.py changed, reloading.
[2025-07-03 22:27:11,596] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-07-03 23:02:21,452] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-07-03 23:16:48,084] [INFO] [django.utils.autoreload] /home/meeh/Desktop/venti2.0/backend/custom_auth/views.py changed, reloading.
[2025-07-03 23:16:51,343] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-07-03 23:17:11,693] [INFO] [django.utils.autoreload] /home/meeh/Desktop/venti2.0/backend/users/authentication.py changed, reloading.
[2025-07-03 23:17:14,947] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-07-03 23:19:45,281] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-07-04 19:46:18,664] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-07-04 20:08:11,844] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-07-04 20:10:50,987] [INFO] [django.utils.autoreload] /home/meeh/Desktop/venti2.0/backend/venti_api/__init__.py changed, reloading.
[2025-07-04 20:11:01,938] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-07-04 20:11:46,441] [INFO] [django.utils.autoreload] /home/meeh/Desktop/venti2.0/backend/venti_api/settings.py changed, reloading.
[2025-07-04 20:11:51,541] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-07-04 20:25:32,525] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-07-04 20:28:53,876] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-07-04 23:16:36,711] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-07-04 23:17:38,200] [INFO] [django.utils.autoreload] /home/meeh/Desktop/venti2.0/backend/venti_api/settings.py changed, reloading.
[2025-07-04 23:17:42,234] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-07-04 23:24:11,868] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-07-04 23:25:17,011] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-07-04 23:26:50,586] [ERROR] [django.request] Internal Server Error: /api/users/profiles/end_activity/
Traceback (most recent call last):
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/users/views.py", line 185, in end_activity
    'duration_minutes': session.duration_minutes,
                        ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'duration_minutes'
[2025-07-04 23:36:46,797] [INFO] [django.utils.autoreload] /home/meeh/Desktop/venti2.0/backend/users/models.py changed, reloading.
[2025-07-04 23:36:53,593] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-07-04 23:37:03,508] [INFO] [django.utils.autoreload] /home/meeh/Desktop/venti2.0/backend/users/serializers.py changed, reloading.
[2025-07-04 23:37:06,865] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-07-04 23:38:33,978] [ERROR] [django.request] Internal Server Error: /api/users/profiles/me/
Traceback (most recent call last):
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/users/views.py", line 90, in me
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 555, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 507, in to_representation
    for field in fields:
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 368, in _readable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
                      ^^^^^^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 1052, in get_fields
    field_names = self.get_field_names(declared_fields, info)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 1148, in get_field_names
    assert field_name in fields, (
           ^^^^^^^^^^^^^^^^^^^^
AssertionError: The field 'skill_levels' was declared on serializer ProfileSerializer, but has not been included in the 'fields' option.
[2025-07-04 23:38:34,535] [ERROR] [django.request] Internal Server Error: /api/users/profiles/me/
Traceback (most recent call last):
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/users/views.py", line 90, in me
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 555, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 507, in to_representation
    for field in fields:
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 368, in _readable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
                      ^^^^^^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 1052, in get_fields
    field_names = self.get_field_names(declared_fields, info)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 1148, in get_field_names
    assert field_name in fields, (
           ^^^^^^^^^^^^^^^^^^^^
AssertionError: The field 'skill_levels' was declared on serializer ProfileSerializer, but has not been included in the 'fields' option.
[2025-07-04 23:52:30,714] [ERROR] [django.request] Internal Server Error: /api/users/profiles/me/
Traceback (most recent call last):
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/users/views.py", line 90, in me
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 555, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 507, in to_representation
    for field in fields:
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 368, in _readable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
                      ^^^^^^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 1052, in get_fields
    field_names = self.get_field_names(declared_fields, info)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 1148, in get_field_names
    assert field_name in fields, (
           ^^^^^^^^^^^^^^^^^^^^
AssertionError: The field 'skill_levels' was declared on serializer ProfileSerializer, but has not been included in the 'fields' option.
[2025-07-04 23:52:31,417] [ERROR] [django.request] Internal Server Error: /api/users/profiles/me/
Traceback (most recent call last):
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/users/views.py", line 90, in me
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 555, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 507, in to_representation
    for field in fields:
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 368, in _readable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
                      ^^^^^^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 1052, in get_fields
    field_names = self.get_field_names(declared_fields, info)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 1148, in get_field_names
    assert field_name in fields, (
           ^^^^^^^^^^^^^^^^^^^^
AssertionError: The field 'skill_levels' was declared on serializer ProfileSerializer, but has not been included in the 'fields' option.
[2025-07-04 23:52:50,781] [ERROR] [django.request] Internal Server Error: /api/users/profiles/me/
Traceback (most recent call last):
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/users/views.py", line 90, in me
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 555, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 507, in to_representation
    for field in fields:
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 368, in _readable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
                      ^^^^^^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 1052, in get_fields
    field_names = self.get_field_names(declared_fields, info)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 1148, in get_field_names
    assert field_name in fields, (
           ^^^^^^^^^^^^^^^^^^^^
AssertionError: The field 'skill_levels' was declared on serializer ProfileSerializer, but has not been included in the 'fields' option.
[2025-07-04 23:52:51,862] [ERROR] [django.request] Internal Server Error: /api/users/profiles/me/
Traceback (most recent call last):
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/users/views.py", line 90, in me
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 555, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 507, in to_representation
    for field in fields:
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 368, in _readable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
                      ^^^^^^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 1052, in get_fields
    field_names = self.get_field_names(declared_fields, info)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 1148, in get_field_names
    assert field_name in fields, (
           ^^^^^^^^^^^^^^^^^^^^
AssertionError: The field 'skill_levels' was declared on serializer ProfileSerializer, but has not been included in the 'fields' option.
[2025-07-04 23:53:16,264] [ERROR] [django.request] Internal Server Error: /api/users/profiles/me/
Traceback (most recent call last):
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/users/views.py", line 90, in me
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 555, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 507, in to_representation
    for field in fields:
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 368, in _readable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
                      ^^^^^^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 1052, in get_fields
    field_names = self.get_field_names(declared_fields, info)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 1148, in get_field_names
    assert field_name in fields, (
           ^^^^^^^^^^^^^^^^^^^^
AssertionError: The field 'skill_levels' was declared on serializer ProfileSerializer, but has not been included in the 'fields' option.
[2025-07-04 23:53:17,254] [ERROR] [django.request] Internal Server Error: /api/users/profiles/me/
Traceback (most recent call last):
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/users/views.py", line 90, in me
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 555, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 507, in to_representation
    for field in fields:
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 368, in _readable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
                      ^^^^^^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 1052, in get_fields
    field_names = self.get_field_names(declared_fields, info)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/meeh/Desktop/venti2.0/backend/venv/lib/python3.12/site-packages/rest_framework/serializers.py", line 1148, in get_field_names
    assert field_name in fields, (
           ^^^^^^^^^^^^^^^^^^^^
AssertionError: The field 'skill_levels' was declared on serializer ProfileSerializer, but has not been included in the 'fields' option.
[2025-07-04 23:55:26,317] [INFO] [django.utils.autoreload] /home/meeh/Desktop/venti2.0/backend/users/serializers.py changed, reloading.
[2025-07-04 23:55:32,264] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-07-05 00:16:33,485] [INFO] [django.utils.autoreload] /home/meeh/Desktop/venti2.0/backend/users/models.py changed, reloading.
[2025-07-05 00:16:42,457] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-07-05 00:20:57,395] [INFO] [django.utils.autoreload] /home/meeh/Desktop/venti2.0/backend/users/models.py changed, reloading.
[2025-07-05 00:21:04,104] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-07-05 00:27:34,531] [INFO] [django.utils.autoreload] /home/meeh/Desktop/venti2.0/backend/users/models.py changed, reloading.
[2025-07-05 00:27:40,827] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-07-05 00:28:19,671] [INFO] [django.utils.autoreload] /home/meeh/Desktop/venti2.0/backend/users/models.py changed, reloading.
[2025-07-05 00:28:22,580] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-07-05 00:28:31,987] [INFO] [django.utils.autoreload] /home/meeh/Desktop/venti2.0/backend/users/serializers.py changed, reloading.
[2025-07-05 00:28:39,707] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-07-05 00:31:45,907] [INFO] [django.utils.autoreload] /home/meeh/Desktop/venti2.0/backend/users/models.py changed, reloading.
[2025-07-05 00:31:52,382] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-07-05 00:34:55,916] [INFO] [django.utils.autoreload] /home/meeh/Desktop/venti2.0/backend/users/models.py changed, reloading.
[2025-07-05 00:35:03,189] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-07-05 00:35:10,882] [INFO] [django.utils.autoreload] /home/meeh/Desktop/venti2.0/backend/users/serializers.py changed, reloading.
[2025-07-05 00:35:16,072] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-07-05 00:35:46,794] [INFO] [django.utils.autoreload] /home/meeh/Desktop/venti2.0/backend/users/models.py changed, reloading.
[2025-07-05 00:35:52,283] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-07-05 01:32:41,127] [INFO] [django.utils.autoreload] /home/meeh/Desktop/venti2.0/backend/users/views.py changed, reloading.
[2025-07-05 01:32:46,563] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
[2025-07-05 02:26:10,957] [INFO] [django.utils.autoreload] /home/meeh/Desktop/venti2.0/backend/users/models.py changed, reloading.
[2025-07-05 02:26:16,918] [INFO] [django.utils.autoreload] Watching for file changes with StatReloader
